# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{AXElements}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mark Rada"]
  s.date = %q{2011-02-08}
  s.description = %q{Takes advantage of the new Bridge Support in Mac OS X Lion to}
  s.email = %q{mrada@marketcircle.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    "lib/AXElements.rb",
    "lib/AXElements/AX.rb",
    "lib/AXElements/Array_ext.rb",
    "lib/AXElements/Element.rb",
    "lib/AXElements/Elements.rb",
    "lib/AXElements/Elements/Application.rb",
    "lib/AXElements/String_ext.rb",
    "lib/AXElements/Traits.rb"
  ]
  s.homepage = %q{http://samurai.marketcircle.com:3000/docs/AXElements}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.requirements = ["BridgeSupport 2.0"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{A simple layer above the Mac OS X Accessibility APIs}
  s.test_files = [
    "spec/AX_spec.rb",
    "spec/Application_spec.rb",
    "spec/Array_ext_spec.rb",
    "spec/Clicking_spec.rb",
    "spec/Element_spec.rb",
    "spec/Notifications_spec.rb",
    "spec/String_ext_spec.rb",
    "spec/Typing_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<AXElements>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.3"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.10"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<reek>, ["~> 1.2.8"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.4"])
      s.add_development_dependency(%q<bluecloth>, ["~> 2.0.10"])
    else
      s.add_dependency(%q<AXElements>, [">= 0"])
      s.add_dependency(%q<activesupport>, ["~> 3.0.3"])
      s.add_dependency(%q<bundler>, ["~> 1.0.10"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<reek>, ["~> 1.2.8"])
      s.add_dependency(%q<yard>, ["~> 0.6.4"])
      s.add_dependency(%q<bluecloth>, ["~> 2.0.10"])
    end
  else
    s.add_dependency(%q<AXElements>, [">= 0"])
    s.add_dependency(%q<activesupport>, ["~> 3.0.3"])
    s.add_dependency(%q<bundler>, ["~> 1.0.10"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<reek>, ["~> 1.2.8"])
    s.add_dependency(%q<yard>, ["~> 0.6.4"])
    s.add_dependency(%q<bluecloth>, ["~> 2.0.10"])
  end
end

